### PR TITLE
Promise chaining and source metadata

### PR DESCRIPTION
**Pull request by pangloss**
I think this really improves both the power and ease of debugging of promises. I'm curious what you think.

Not sure about the name `chain`, considered `bind` as well but thought that may be confusing.

### CODE REVIEW

**Comment by bodil** [comment]
Do you have a use case for `chain`? I'm not sure I see where it's useful...

**Comment by pangloss** [comment]
Sure, for instance, in an app that I'm writing, I make a lot of API calls. Say I need to request some records but only want their IDs, but the API doesn't expose a request in the precise shape I need, I can do something like this: 

``` clojure
(chain (request-records->promise) #(map :id %))
```

This case also illustrates the usefulness of the promise tracking its source: If my user wants to cancel the request (say it is slow), I can use a simple function to extract a seq of promise sources (the leaves in the promise tree), and cancel the requests easily.

**Comment by bodil** [comment]
Ah, that makes sense. You're right about it needing a better name, though. :)

Not sure about the promise metadata stuff - I do agree that it's useful, I just have this feeling there's a more idiomatic way to implement it. Let me meditate on it for a bit...

**Comment by pangloss** [comment]
[This](https://github.com/Obvious/kew) JS promise library uses `then` to do the same thing. Alternatively might it would be more idiomatic to extend the promise with IFn to do this?

**Pull request closed without merging**
